# Generated by Django 4.2.5 on 2023-09-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Estate',
        ),
    ]
