# Generated by Django 4.2.5 on 2023-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_estate_areainner_estate_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='AreaInner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estate',
            name='Bathrooms',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estate',
            name='BedroomsInner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
